# Generated by Django 3.2.4 on 2021-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='twitter',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='LinkedIn'),
        ),
    ]
